"""Add milestones field to user profiles for AI memory system

Revision ID: bdd877e04610
Revises: ef5ee746e09b
Create Date: 2025-10-29 23:09:43.492754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd877e04610'
down_revision: Union[str, Sequence[str], None] = 'ef5ee746e09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('milestones', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'milestones')
    # ### end Alembic commands ###
